### PR TITLE
Assignment 2: Team with Oskar Kalm

### PR DESCRIPTION
**Pull request by farisitum**

### CODE REVIEW

**Comment by cimslab** [comment]
Hi Faris, I see that you have posted some changes. Please make sure that in the root of your folder there is a file called `about.html` that is the only page that my website is going to look for in your folder. If it cannot find it, it won't work
it needs to be like this:
image
The same applies to Oskar.

Please let me know if you have further questions

**Comment by farisitum** [comment]
Hello Nico,

Thanks for letting me know. Did you receive my updated pull request with
the correct root folder?

**Comment by cimslab** [comment]
Faris, you need to be very careful about the file naming. Your html is looking for a file called `main.js` 
image
and your folder only has a `Main.js` (notice the capital M). For coding, `M` and `m` are totally different characters, so your html will never find it.
image

Please revise.

**Comment by farisitum** [comment]
Professor Nico,

Oh man, sorry for the back and forth. I think this should be better.

Please let me know…

**Comment by nicoarellano** [comment]
This is just a comment, I have not received your updated code. Make sure you commit, push and create a pull request

**Comment by farisitum** [comment]
😬 thanks for letting me know.

Maybe now?

**Pull request merged**
