### PR TITLE
Final Assignment Upload

### PR DESCRIPTION
**Pull request by Dennis-Av**
Adding and Changing Files for the final

### CODE REVIEW

**Comment by nicoarellano** [comment]
Hi Dennis, can you make sure to follow the following steps in order to create your BIM viewer:
move the folder outside your assignment folder
`npm run build`
when it is done building, take the dist folder and move it to your assignment folder, but rename it `bim`
Then, create a new pull request, making sure only those files are committed instead of all the other files that are not important for the assignment:
image

**Comment by Dennis-Av** [comment]
Good Morning Nico, sorry about that - I meant to remove the bim folder as I originally wanted to add a Revit file however don’t have time to anymore with everything I still have to do for studio. I can’t see the most recent commit (final) on brightspace still, is there something I need to correct in the pull request?

Thanks,
Dennis

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicoarellano** [comment]
Ok, I'll try to retrive the files from your

**Comment by nicoarellano** [comment]
I have added the files, please sync and pull to get the changes.
The final assignment is looking great, you just need to fix the layout a little bit (final/index.html)
I am publishing it now, it should be up in the next 10 minutes

**Pull request closed without merging**
