### PR TITLE
updates for assignment 2

### PR DESCRIPTION
**Pull request by oskarkalm**

### CODE REVIEW

**Comment by nicoarellano** [comment]
Looks amazing! I am just missing your mesh from the photogrammetry exercise.

**Comment by oskarkalm** [comment]
Great thank you. Faris and I Worked together so I'm unsure as to why were having difficulties from one another. However, I will update the mesh file now.

**Comment by oskarkalm** [comment]
Additionally, my push/ pull access to our repository is now blocked for some reason. I am unable to push the model file.

**Comment by nicoarellano** [comment]
Try pulling first and then pushing again.
How big is your mesh? If it is larger than 25 MB it won't allow you. You will have to reduce the file size.

**Comment by oskarkalm** [comment]
The mesh only works in the VS code (and shows in live server) when uncompressed. If I use blender's compression tool, and relink the mesh to my .js code, the mesh doesn't show up in live server. I'm unsure on how to compress the mesh and still have it function correctly. Will play around with it and see what happens.

**Pull request merged**
