### PR TITLE
Added a star background to my 3d elements section

### PR DESCRIPTION
**Pull request by apap19**

### CODE REVIEW

**Comment by nicoarellano** [comment]
Andree-ann don't forget to sync and push before commiting. You want to be at the same stage as the course page. Let me know if you have any questions. Worst case scenario you post all your code through Brightspace.
Have a good weekend

**Comment by nicoarellano** [comment]
Andree-anne, , if pushing doesn't work. Go directly into GitHub and copy paste your changes. Go into your main.js edit file.
Try that it may work. Be careful because it there are bugs, GitHub will not tell you. So only copy paste your changes that you are sure are fine.

Let me know if you have questions.

**Comment by apap19** [comment]
Professor I believe your sending me messages that are meant for Andree-anne, see below

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by apap19** [comment]
My GitHub works fine I hope, i sent a screenshot of what it looks like  on my computer on brightspace. If you need me to resubmit let me know.

Best,
Anthony
________________________________

**Pull request closed without merging**
