### PR TITLE
Pull 1

### PR DESCRIPTION
**Pull request by benbsegal**

### CODE REVIEW

**Comment by nicoarellano** [comment]
Hi Ben, as we discussed yesterday, I would encourage you to focus on the Three js part of the assignment and then if that works, you can look into adding more complex parts.
For now I will close this pull reques without merging, because adding 100+ images to get an animation is cool but a bit out of the scope for this assignment.
Please let me know if you have questions

**Comment by nicoarellano** [comment]
Hi Ben, will you resubmit your assignment? I don't want to penalize you for late assignments because I know you have been working.

**Comment by benbsegal** [comment]
Hey Nico, 
I uploaded the files yesterday and thought it went through but seems I forgot to commit it. I just committed. Please let me know if it went through.

**Comment by nicoarellano** [comment]
No worries, I was just making sure. I just merged it. It should be updated in around 5 minutes.

**Pull request closed without merging**
