### PR TITLE
final assignment submission trial2

### PR DESCRIPTION
**Pull request by maisjoudeh**
I cloned the repo again

### CODE REVIEW

**Comment by nicoarellano** [comment]
Mais, I am trying to get your files, but I can't find them:
image
image
The only thing that I see in this PR is that you are deleting your previous assignments.
Please make sure you have your final submission in the 'final' folder. (not the same as 'Final', be very careful about capitalization)
It must be a file called index.html, which I don't see.
Please try again. I am submitting the grades now and don't want to fail you.

**Comment by maisjoudeh** [comment]
I will try a new PR
It will include edits to my first assignment because all the codes got mixed up together.
It also includes all the assignments for the final assignment, this is how it looks on my vs code:
[cid:17757cad-dd3c-471e-8fc1-3b883bd16579]
[cid:b4eb2e74-edc7-4780-9afd-661ee2c94969]

________________________________

**Comment by nicoarellano** [comment]
It did not work.
As mentioned in my previous message, this PR deleted your map and your 'final' folder.
I was not able to find your files.
If you sync now, you will see that your folders got deleted and nothing useful shows up.
Please review ASAP!

**Comment by maisjoudeh** [comment]
my final folder is in the capital letter, i cant edit it or change it or even create a new one with the label final in a small folder-
[cid:1f64cc14-5918-4699-a5ec-86f01cfa1488]
 These are my staged changes:
[cid:cc6ef309-e4cd-4993-9eec-4c5afcea3b22]
I then clicked commit (after making sure that my fork is synced from github):
[cid:dc2be307-3b7b-4874-b5c9-23c976735cb1]

And then i created a new pull request making sure that i am on the same branch i made the changes on  (dev):
[cid:9e8a5647-dcbf-4454-b8fa-31d9d815f9b6]

There should be 36 changes..

Best Regards,

Mais Joudeh
101180890

________________________________

**Pull request merged**
